name: dmp
dependencies:
- python=3.9
- pandas
- scikit-learn
- pip
- scipy
- numpy
- conda-forge::tensorflow >= 2.7
- simplejson
- libpq
- pip:
  - pyarrow >= 10
  - psycopg >= 3
  - psycopg_pool >= 3
  - pytest
  - tensorflow_datasets
  - pmlb
  - connectorx
  - pathos


  
