name: dmp
dependencies:
- python=3.9
- pandas
- jupyter
- matplotlib
- scikit-learn
- statsmodels
- seaborn
- pip
- scipy
- numpy
- sqlalchemy
- psycopg2
- pyarrow
- tensorflow-gpu>=2.7
- cudnn>=8
- simplejson
- pip:
  - pytest
  - tensorflow_datasets
  - pmlb
  - keras_buoy
  - orjson
  - connectorx
  - pathos


  
