name: dmp
dependencies:
- python >= 3.10
- pandas
- scikit-learn
- pip
- scipy
- numpy
- tensorflow >= 2.11
- simplejson
- libpq
- bzip2
- lz4
- pip:
  - pyarrow >= 12
  - psycopg[binary] >= 3
  - psycopg_pool >= 3
  - pytest
  - tensorflow_datasets
  - pmlb
  - pathos



