name: dmp
dependencies:
- python=3.8
- pandas
- jupyter
- matplotlib
- scikit-learn
- statsmodels
- seaborn
- pip
- scipy=1.4.1
- numpy<1.19.0
- sqlalchemy
- psycopg2
- pip:
  - pytest
  - tensorflow
  - tensorflow_datasets
  - pmlb
  - keras


  
