name: dmp
dependencies:
- python=3.9
- pandas
- jupyter
- matplotlib
- scikit-learn
- statsmodels
- seaborn
- pip
- scipy
- numpy
- sqlalchemy
- psycopg2
- conda-forge::tensorflow >= 2.7
- simplejson
- pip:
  - pyarrow >= 10
  - pytest
  - tensorflow_datasets
  - pmlb
  - orjson
  - connectorx
  - pathos


  
