name: dmp
dependencies:
- python=3.8
- pandas
- jupyter
- matplotlib
- scikit-learn
- statsmodels
- seaborn
- pip
- scipy=1.4.1
- numpy
- sqlalchemy
- psycopg2
- pyarrow
- tensorflow>=2.6
- ujson
- pip:
  - pytest
  - tensorflow_datasets
  - pmlb
  - keras_buoy
  - orjson
  - connectorx
  - pathos


  
