name: dmp
dependencies:
- python >= 3.10
- setuptools >= 63
- pandas
- scikit-learn
- pip
- scipy
- numpy
- simplejson
- libpq
- bzip2
- lz4
- h5py
- hdf5plugin
- mamba
- pip:
  - tensorflow[with-cuda] >= 2.16
  - pyarrow >= 16
  - psycopg[binary] >= 3
  - psycopg_pool >= 3
  - pytest
  - tensorflow_datasets
  - pmlb
  - pathos



