[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dmp"
version = "2.0.1"
description = "An experimental framework for deep learning."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE.md"}
