import pytest

from dmp.experiment.structure.algorithm.network_json_deserializer import NetworkJSONDeserializer
from dmp.experiment.structure.algorithm.network_json_serializer import NetworkJSONSerializer


@pytest.mark.parametrize("serialized", [
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[431],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[3],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[4],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[5],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[6],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[7],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[8],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[9],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[10],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[11],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[12],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[13],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[14],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[15],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[16],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[17],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[18],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[19],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[20],"label":0,"shape":[20],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[1766022],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[3],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[4],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[5],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[6],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[7],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[8],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[9],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[10],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[11],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[12],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[13],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[14],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[15],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[16],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[17],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[18],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[19],"label":0,"shape":[1364],"type":"NDense"},{"activation":"relu","inputs":[20],"label":0,"shape":[1364],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[431],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[8],"type":"NDense"},{"activation":"relu","inputs":[3],"label":0,"shape":[9],"type":"NDense"},{"activation":"relu","inputs":[4],"label":0,"shape":[11],"type":"NDense"},{"activation":"relu","inputs":[5],"label":0,"shape":[12],"type":"NDense"},{"activation":"relu","inputs":[6],"label":0,"shape":[13],"type":"NDense"},{"activation":"relu","inputs":[7],"label":0,"shape":[14],"type":"NDense"},{"activation":"relu","inputs":[8],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[9],"label":0,"shape":[17],"type":"NDense"},{"activation":"relu","inputs":[10],"label":0,"shape":[18],"type":"NDense"},{"activation":"relu","inputs":[11],"label":0,"shape":[19],"type":"NDense"},{"activation":"relu","inputs":[12],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[13],"label":0,"shape":[22],"type":"NDense"},{"activation":"relu","inputs":[14],"label":0,"shape":[23],"type":"NDense"},{"activation":"relu","inputs":[15],"label":0,"shape":[24],"type":"NDense"},{"activation":"relu","inputs":[16],"label":0,"shape":[25],"type":"NDense"},{"activation":"relu","inputs":[17],"label":0,"shape":[26],"type":"NDense"},{"activation":"relu","inputs":[18],"label":0,"shape":[28],"type":"NDense"},{"activation":"relu","inputs":[19],"label":0,"shape":[29],"type":"NDense"},{"activation":"relu","inputs":[20],"label":0,"shape":[30],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[1766022],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[128],"type":"NDense"},{"activation":"relu","inputs":[3],"label":0,"shape":[248],"type":"NDense"},{"activation":"relu","inputs":[4],"label":0,"shape":[369],"type":"NDense"},{"activation":"relu","inputs":[5],"label":0,"shape":[490],"type":"NDense"},{"activation":"relu","inputs":[6],"label":0,"shape":[610],"type":"NDense"},{"activation":"relu","inputs":[7],"label":0,"shape":[731],"type":"NDense"},{"activation":"relu","inputs":[8],"label":0,"shape":[852],"type":"NDense"},{"activation":"relu","inputs":[9],"label":0,"shape":[972],"type":"NDense"},{"activation":"relu","inputs":[10],"label":0,"shape":[1093],"type":"NDense"},{"activation":"relu","inputs":[11],"label":0,"shape":[1214],"type":"NDense"},{"activation":"relu","inputs":[12],"label":0,"shape":[1335],"type":"NDense"},{"activation":"relu","inputs":[13],"label":0,"shape":[1455],"type":"NDense"},{"activation":"relu","inputs":[14],"label":0,"shape":[1576],"type":"NDense"},{"activation":"relu","inputs":[15],"label":0,"shape":[1697],"type":"NDense"},{"activation":"relu","inputs":[16],"label":0,"shape":[1817],"type":"NDense"},{"activation":"relu","inputs":[17],"label":0,"shape":[1938],"type":"NDense"},{"activation":"relu","inputs":[18],"label":0,"shape":[2059],"type":"NDense"},{"activation":"relu","inputs":[19],"label":0,"shape":[2179],"type":"NDense"},{"activation":"relu","inputs":[20],"label":0,"shape":[2300],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[431],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[8],"type":"NDense"},{"activation":"relu","inputs":[3],"label":0,"shape":[8],"type":"NDense"},{"activation":"relu","inputs":[4],"label":0,"shape":[9],"type":"NDense"},{"activation":"relu","inputs":[5],"label":0,"shape":[10],"type":"NDense"},{"activation":"relu","inputs":[6],"label":0,"shape":[11],"type":"NDense"},{"activation":"relu","inputs":[7],"label":0,"shape":[12],"type":"NDense"},{"activation":"relu","inputs":[8],"label":0,"shape":[13],"type":"NDense"},{"activation":"relu","inputs":[9],"label":0,"shape":[14],"type":"NDense"},{"activation":"relu","inputs":[10],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[11],"label":0,"shape":[17],"type":"NDense"},{"activation":"relu","inputs":[12],"label":0,"shape":[18],"type":"NDense"},{"activation":"relu","inputs":[13],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[14],"label":0,"shape":[22],"type":"NDense"},{"activation":"relu","inputs":[15],"label":0,"shape":[24],"type":"NDense"},{"activation":"relu","inputs":[16],"label":0,"shape":[26],"type":"NDense"},{"activation":"relu","inputs":[17],"label":0,"shape":[28],"type":"NDense"},{"activation":"relu","inputs":[18],"label":0,"shape":[31],"type":"NDense"},{"activation":"relu","inputs":[19],"label":0,"shape":[34],"type":"NDense"},{"activation":"relu","inputs":[20],"label":0,"shape":[37],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[1766022],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[10],"type":"NDense"},{"activation":"relu","inputs":[3],"label":0,"shape":[14],"type":"NDense"},{"activation":"relu","inputs":[4],"label":0,"shape":[20],"type":"NDense"},{"activation":"relu","inputs":[5],"label":0,"shape":[28],"type":"NDense"},{"activation":"relu","inputs":[6],"label":0,"shape":[39],"type":"NDense"},{"activation":"relu","inputs":[7],"label":0,"shape":[55],"type":"NDense"},{"activation":"relu","inputs":[8],"label":0,"shape":[78],"type":"NDense"},{"activation":"relu","inputs":[9],"label":0,"shape":[110],"type":"NDense"},{"activation":"relu","inputs":[10],"label":0,"shape":[155],"type":"NDense"},{"activation":"relu","inputs":[11],"label":0,"shape":[219],"type":"NDense"},{"activation":"relu","inputs":[12],"label":0,"shape":[309],"type":"NDense"},{"activation":"relu","inputs":[13],"label":0,"shape":[436],"type":"NDense"},{"activation":"relu","inputs":[14],"label":0,"shape":[615],"type":"NDense"},{"activation":"relu","inputs":[15],"label":0,"shape":[867],"type":"NDense"},{"activation":"relu","inputs":[16],"label":0,"shape":[1224],"type":"NDense"},{"activation":"relu","inputs":[17],"label":0,"shape":[1726],"type":"NDense"},{"activation":"relu","inputs":[18],"label":0,"shape":[2436],"type":"NDense"},{"activation":"relu","inputs":[19],"label":0,"shape":[3437],"type":"NDense"},{"activation":"relu","inputs":[20],"label":0,"shape":[4849],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[431],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[3],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[4],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[5],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[6],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[7],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[8],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[9],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[10],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[11],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[12],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[13],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[14],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[15],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[16],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[17],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[18],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[19],"label":0,"shape":[15],"type":"NDense"},{"activation":"relu","inputs":[20],"label":0,"shape":[148],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[1766022],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',
    '[{"activation":"softmax","inputs":[1],"label":0,"shape":[7],"type":"NDense"},{"activation":"relu","inputs":[2],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[3],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[4],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[5],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[6],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[7],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[8],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[9],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[10],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[11],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[12],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[13],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[14],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[15],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[16],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[17],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[18],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[19],"label":0,"shape":[1112],"type":"NDense"},{"activation":"relu","inputs":[20],"label":0,"shape":[11125],"type":"NDense"},{"inputs":[],"label":0,"shape":[11],"type":"NInput"}]',

])
def test_network_json_serializer(serialized):
    deserialized = NetworkJSONDeserializer(serialized)()
    reserialized = NetworkJSONSerializer(deserialized)()
    assert reserialized == serialized
