'''
Configuration key strings for configuring Keras objects including Keras Layer objects
'''

# import dmp.keras_interface.keras_keys as keras_keys
activation: str = 'activation'
activity_regularizer: str = 'activity_regularizer'
axis: str = 'axis'
batch_normalization: str = 'batch_normalization'
bias_constraint: str = 'bias_constraint'
bias_initializer: str = 'bias_initializer'
bias_regularizer: str = 'bias_regularizer'
conv_layer_factory: str = 'conv_layer_factory'
data_format: str = 'data_format'
dilation_rate: str = 'dilation_rate'
dmp_layer_prefix : str = 'dmp_layer_'
epochs: str = 'epochs'
filters: str = 'filters'
get_weights: str = 'get_weights'
groups: str = 'groups'
initialization : str = 'initialization'
keepdims : str = 'keepdims'
kernel_constraint: str = 'kernel_constraint'
kernel_initializer: str = 'kernel_initializer'
kernel_regularizer: str = 'kernel_regularizer'
kernel_size: str = 'kernel_size'
name:str = 'name'
padding: str = 'padding'
pool_size: str = 'pool_size'
set_weights : str = 'set_weights'
shape: str = 'shape'
strides: str = 'strides'
units: str = 'units'
use_bias: str = 'use_bias'
